### ISSUE TITLE
Remove 2021 recap

### ISSUE THREAD

**Issue by MartinSStewart** [sylbru/is-elm-dead#2]
It's 2023 now! Showing the 2021 recap is probably counter productive at this point so it should probably be removed from the page?

**Comment by sylbru** [comment]
You’re right! Do you think that applies less to the links to Evan’s posts that also date back to 2021?

**Comment by MartinSStewart** [comment]
Yeah, I think you should keep Evan's posts. It's the most recent news, even if that happens to be from 2021.

Edit: Hopefully a 2022 recap is released but an alternative is https://www.elmweekly.nl/ or https://www.elmcraft.org/

**Comment by sylbru** [comment]
Done now! And I added links to Elm Weekly and Elmcraft (also Elm Radio), great idea. Thanks!
