### ISSUE TITLE
Consider this possible addition

### ISSUE THREAD

**Issue by lucamug** [sylbru/is-elm-dead#4]
https://twitter.com/luca_mug/status/1697729481556082916

**Comment by sylbru** [comment]
Ha this is amazing! Can you point me to the Slack discussion where it was initially posted?

**Comment by sylbru** [comment]
Ok I found it: https://elmlang.slack.com/archives/C0NLYJWSZ/p1693511526698109

**Comment by sylbru** [comment]
Now included! :)
