### ISSUE TITLE
Elm on the backend talk has happened

### ISSUE THREAD

**Issue by lpil** [sylbru/is-elm-dead#5]
Hello! The copy talks about the Elm on the backend talk as if it has not happened yet, but it has now taken place.

**Comment by sylbru** [comment]
Hi! I wrote the sentence with that in mind, my use of the future tense referring to the fact that the video hasn’t been published yet, even though the talk as happened, but it’s probably bad English on my part. Do you think it would be clearer as something like this?

> His GOTO Aarhus 2023 talk “Elm on the Backend” surely brought more details about these explorations, but we’ll have to wait for the video to be released in order to know more.

**Comment by sylbru** [comment]
I changed this whole paragraph, the whole thing is more clear and up to date now. (Always happy to hear any suggestion though)
